# This is the configuration file for deploying this API to
# Google App Engine.
runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1.7
  disk_size_gb: 10
endpoints_api_service:
  name: maailmankaikkeus-192918.appspot.com
  config_id: 2019-02-13r0